version: '3.8'
services:
  jupyterlab:
    user: root
    build:
      context: ./docker
      dockerfile: jupyterlab/Dockerfile
    ports:
      - '8777:8888'
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
  
  gpu-jupyterlab:
    user: root
    build: 
      context: ./docker
      dockerfile: gpu-jupyterlab/Dockerfile
    ports:
      - 8778:8888
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    profiles: ["gpu"]
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    