version: '3.8'
services:
  jupyter101:
    user: root
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - '8777:8888'
    volumes:
      - /notebooks:/home/jovyan
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - CHOWN_HOME=yes
      - CHOWN_EXTRA_OPTS='-R'
    