version: '3.8'
services:
  jupyter:
    build:
      context: .
      dockerfile: ./notebooks/Dockerfile
    ports:
      - '8889:8888'
    volumes:
      - .:/home/jovyan
    environment:
      - JUPYTER_ENABLE_LAB=True